import * as fs from "fs";
import * as os from "os";
import * as path from "path";

export type ShellType = "bash" | "zsh" | "fish";

/**
 * Detect the user's shell from $SHELL environment variable.
 * Returns null if the shell cannot be determined.
 */
export function detectShell(): ShellType | null {
  const shell = process.env.SHELL;
  if (!shell) return null;

  const base = path.basename(shell);
  if (base === "bash") return "bash";
  if (base === "zsh") return "zsh";
  if (base === "fish") return "fish";
  return null;
}

export function generateBashScript(): string {
  return `# william shell completions for bash
# Generated by: william completions --shell bash
# Add to ~/.bashrc or ~/.bash_profile:
#   source <(william completions --shell bash)
#   OR
#   william completions --shell bash > ~/.william/completions/william.bash && source ~/.william/completions/william.bash

_william_completions() {
  local cur prev words cword
  _init_completion || return

  local result
  result="$(william _completions --command "\${words[1]:-}" --position "$cword" -- "\${words[@]}" 2>/dev/null)"

  if [[ -n "$result" ]]; then
    COMPREPLY=($(compgen -W "$result" -- "$cur"))
  fi
}

complete -F _william_completions william
`;
}

export function generateZshScript(): string {
  return `# william shell completions for zsh
# Generated by: william completions --shell zsh
# Add to ~/.zshrc:
#   source <(william completions --shell zsh)
#   OR
#   william completions --shell zsh > ~/.william/completions/william.zsh && source ~/.william/completions/william.zsh

_william_completions() {
  local -a completions
  local result

  result="$(william _completions --command "\${words[2]:-}" --position "$CURRENT" -- "\${words[@]}" 2>/dev/null)"

  if [[ -n "$result" ]]; then
    completions=("\${(@f)result}")
    compadd -a completions
  fi
}

compdef _william_completions william
`;
}

export function generateFishScript(): string {
  return `# william shell completions for fish
# Generated by: william completions --shell fish
# Save to ~/.config/fish/completions/william.fish:
#   william completions --shell fish > ~/.config/fish/completions/william.fish

function __william_completions
  set -l tokens (commandline -opc)
  set -l current (commandline -ct)
  set -l count (count $tokens)

  set -l cmd ""
  if test $count -ge 2
    set cmd $tokens[2]
  end

  william _completions --command "$cmd" --position $count -- $tokens 2>/dev/null
end

complete -c william -f -a '(__william_completions)'
`;
}

export function generateScript(shell: ShellType): string {
  switch (shell) {
    case "bash":
      return generateBashScript();
    case "zsh":
      return generateZshScript();
    case "fish":
      return generateFishScript();
  }
}

function getShellExtension(shell: ShellType): string {
  switch (shell) {
    case "bash":
      return "bash";
    case "zsh":
      return "zsh";
    case "fish":
      return "fish";
  }
}

function getProfilePath(shell: ShellType): string {
  const home = os.homedir();
  switch (shell) {
    case "bash":
      // On macOS, prefer ~/.bash_profile; on Linux, prefer ~/.bashrc
      if (process.platform === "darwin") {
        return path.join(home, ".bash_profile");
      }
      return path.join(home, ".bashrc");
    case "zsh":
      return path.join(home, ".zshrc");
    case "fish":
      // Fish uses a completions directory, no profile sourcing needed
      return path.join(home, ".config", "fish", "completions", "william.fish");
  }
}

function isAlreadyInstalled(profilePath: string, sourceLine: string): boolean {
  if (!fs.existsSync(profilePath)) return false;
  const content = fs.readFileSync(profilePath, "utf-8");
  return content.includes(sourceLine);
}

export function installCompletions(shell: ShellType): void {
  const home = os.homedir();
  const ext = getShellExtension(shell);
  const completionsDir = path.join(home, ".william", "completions");
  const scriptPath = path.join(completionsDir, `william.${ext}`);
  const script = generateScript(shell);

  if (shell === "fish") {
    // Fish: write directly to the Fish completions directory
    const fishCompletionsDir = path.join(
      home,
      ".config",
      "fish",
      "completions",
    );
    fs.mkdirSync(fishCompletionsDir, { recursive: true });
    const fishPath = path.join(fishCompletionsDir, "william.fish");

    // Also write to ~/.william/completions/ for consistency
    fs.mkdirSync(completionsDir, { recursive: true });
    fs.writeFileSync(scriptPath, script);

    // Check if already installed
    if (
      fs.existsSync(fishPath) &&
      fs.readFileSync(fishPath, "utf-8") === script
    ) {
      console.log(
        `Completions already installed at ${fishPath}. Nothing to do.`,
      );
      return;
    }

    fs.writeFileSync(fishPath, script);
    console.log(`Completion script written to: ${scriptPath}`);
    console.log(`Fish completions installed to: ${fishPath}`);
  } else {
    // Bash/Zsh: write script to ~/.william/completions/ and source from profile
    fs.mkdirSync(completionsDir, { recursive: true });
    fs.writeFileSync(scriptPath, script);

    const profilePath = getProfilePath(shell);
    const sourceLine = `source "${scriptPath}"`;

    if (isAlreadyInstalled(profilePath, sourceLine)) {
      console.log(
        `Completions already installed in ${profilePath}. Nothing to do.`,
      );
      return;
    }

    // Append source line to profile
    const profileExists = fs.existsSync(profilePath);
    if (profileExists) {
      const content = fs.readFileSync(profilePath, "utf-8");
      const separator = content.endsWith("\n") ? "" : "\n";
      fs.appendFileSync(
        profilePath,
        `${separator}\n# william shell completions\n${sourceLine}\n`,
      );
    } else {
      fs.writeFileSync(
        profilePath,
        `# william shell completions\n${sourceLine}\n`,
      );
    }

    console.log(`Completion script written to: ${scriptPath}`);
    console.log(`Profile updated: ${profilePath}`);
  }

  console.log(
    `\nRestart your shell or run: source ${shell === "fish" ? getProfilePath(shell) : getProfilePath(shell)} to enable completions.`,
  );
}
