import * as fs from "fs";
import * as os from "os";
import * as path from "path";

export type ShellType = "bash" | "zsh" | "fish";

/**
 * Detect the user's shell from $SHELL environment variable.
 * Returns null if the shell cannot be determined.
 */
export function detectShell(): ShellType | null {
  const shell = process.env.SHELL;
  if (!shell) return null;

  const base = path.basename(shell);
  if (base === "bash") return "bash";
  if (base === "zsh") return "zsh";
  if (base === "fish") return "fish";
  return null;
}

export const WILLIAM_COMMANDS = [
  "new",
  "init",
  "start",
  "stop",
  "status",
  "archive",
  "list",
  "migrate",
  "prd",
  "problem",
  "revise",
  "pr",
  "completions",
] as const;

export const COMMAND_FLAGS: Record<
  string,
  { flag: string; description: string }[]
> = {
  new: [{ flag: "--prd", description: "PRD file path" }],
  start: [
    { flag: "--max-iterations", description: "Maximum iterations" },
    { flag: "--tool", description: "AI tool adapter" },
  ],
  prd: [{ flag: "--output", description: "Output path for PRD file" }],
  pr: [
    { flag: "--draft", description: "Create PR as draft" },
    { flag: "--dry-run", description: "Preview without creating" },
  ],
  completions: [
    { flag: "--shell", description: "Shell type (bash, zsh, fish)" },
    { flag: "--install", description: "Install to shell profile" },
  ],
};

export function generateBashScript(): string {
  const cmds = WILLIAM_COMMANDS.join(" ");
  const bashCaseEntries = Object.entries(COMMAND_FLAGS)
    .map(([cmd, flags]) => {
      const flagNames = flags.map((f) => f.flag).join(" ");
      return `      ${cmd}) flags="$flags ${flagNames}" ;;`;
    })
    .join("\n");
  return `# william shell completions for bash
# Generated by: william completions --shell bash
# Add to ~/.bashrc or ~/.bash_profile:
#   source <(william completions --shell bash)
#   OR
#   william completions --shell bash > ~/.william/completions/william.bash && source ~/.william/completions/william.bash

_william_completions() {
  local cur prev words cword
  _init_completion || return

  # Complete command names at position 1
  if [[ "$cword" -eq 1 ]]; then
    local commands="${cmds}"
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return
  fi

  # Complete flags when current word starts with -
  if [[ "$cur" == -* ]]; then
    local cmd="\${words[1]}"
    local flags="--help"
    case "$cmd" in
${bashCaseEntries}
    esac
    COMPREPLY=($(compgen -W "$flags" -- "$cur"))
    return
  fi

  # For other positions, delegate to the dynamic completions subcommand
  local result
  result="$(william _completions --command "\${words[1]:-}" --position "$cword" -- "\${words[@]}" 2>/dev/null)"

  if [[ -n "$result" ]]; then
    COMPREPLY=($(compgen -W "$result" -- "$cur"))
  fi
}

complete -F _william_completions william
`;
}

export function generateZshScript(): string {
  const cmds = WILLIAM_COMMANDS.join(" ");
  const zshCaseEntries = Object.entries(COMMAND_FLAGS)
    .map(([cmd, flags]) => {
      const flagNames = flags.map((f) => f.flag).join(" ");
      return `      ${cmd}) flags+=(${flagNames}) ;;`;
    })
    .join("\n");
  return `# william shell completions for zsh
# Generated by: william completions --shell zsh
# Add to ~/.zshrc:
#   source <(william completions --shell zsh)
#   OR
#   william completions --shell zsh > ~/.william/completions/william.zsh && source ~/.william/completions/william.zsh

_william_completions() {
  local -a completions
  local result

  # Complete command names at position 2 (zsh is 1-indexed; position 1 is "william")
  if [[ "$CURRENT" -eq 2 ]]; then
    local -a commands=(${cmds})
    _describe 'command' commands
    return
  fi

  # Complete flags when current word starts with -
  if [[ "$PREFIX" == -* ]]; then
    local cmd="\${words[2]}"
    local -a flags=(--help)
    case "$cmd" in
${zshCaseEntries}
    esac
    compadd -- $flags
    return
  fi

  # For other positions, delegate to the dynamic completions subcommand
  result="$(william _completions --command "\${words[2]:-}" --position "$CURRENT" -- "\${words[@]}" 2>/dev/null)"

  if [[ -n "$result" ]]; then
    completions=("\${(@f)result}")
    compadd -a completions
  fi
}

compdef _william_completions william
`;
}

export function generateFishScript(): string {
  const cmdEntries = WILLIAM_COMMANDS.map(
    (cmd) => `complete -c william -f -n '__william_needs_command' -a '${cmd}'`,
  ).join("\n");
  const fishFlagEntries = Object.entries(COMMAND_FLAGS)
    .flatMap(([cmd, flags]) =>
      flags.map((f) => {
        const longFlag = f.flag.replace(/^--/, "");
        return `complete -c william -f -n '__william_using_command ${cmd}' -l ${longFlag} -d '${f.description}'`;
      }),
    )
    .join("\n");
  return `# william shell completions for fish
# Generated by: william completions --shell fish
# Save to ~/.config/fish/completions/william.fish:
#   william completions --shell fish > ~/.config/fish/completions/william.fish

function __william_needs_command
  set -l tokens (commandline -opc)
  test (count $tokens) -eq 1
end

function __william_using_command
  set -l tokens (commandline -opc)
  test (count $tokens) -ge 2; and test $tokens[2] = $argv[1]
end

function __william_completions
  set -l tokens (commandline -opc)
  set -l count (count $tokens)

  set -l cmd ""
  if test $count -ge 2
    set cmd $tokens[2]
  end

  william _completions --command "$cmd" --position $count -- $tokens 2>/dev/null
end

# Static command name completions
${cmdEntries}

# Per-command flag completions
${fishFlagEntries}

# Dynamic completions for flags and arguments
complete -c william -f -n 'not __william_needs_command' -a '(__william_completions)'
`;
}

export function generateScript(shell: ShellType): string {
  switch (shell) {
    case "bash":
      return generateBashScript();
    case "zsh":
      return generateZshScript();
    case "fish":
      return generateFishScript();
  }
}

function getShellExtension(shell: ShellType): string {
  switch (shell) {
    case "bash":
      return "bash";
    case "zsh":
      return "zsh";
    case "fish":
      return "fish";
  }
}

function getProfilePath(shell: ShellType): string {
  const home = os.homedir();
  switch (shell) {
    case "bash":
      // On macOS, prefer ~/.bash_profile; on Linux, prefer ~/.bashrc
      if (process.platform === "darwin") {
        return path.join(home, ".bash_profile");
      }
      return path.join(home, ".bashrc");
    case "zsh":
      return path.join(home, ".zshrc");
    case "fish":
      // Fish uses a completions directory, no profile sourcing needed
      return path.join(home, ".config", "fish", "completions", "william.fish");
  }
}

function isAlreadyInstalled(profilePath: string, sourceLine: string): boolean {
  if (!fs.existsSync(profilePath)) return false;
  const content = fs.readFileSync(profilePath, "utf-8");
  return content.includes(sourceLine);
}

export function installCompletions(shell: ShellType): void {
  const home = os.homedir();
  const ext = getShellExtension(shell);
  const completionsDir = path.join(home, ".william", "completions");
  const scriptPath = path.join(completionsDir, `william.${ext}`);
  const script = generateScript(shell);

  if (shell === "fish") {
    // Fish: write directly to the Fish completions directory
    const fishCompletionsDir = path.join(
      home,
      ".config",
      "fish",
      "completions",
    );
    fs.mkdirSync(fishCompletionsDir, { recursive: true });
    const fishPath = path.join(fishCompletionsDir, "william.fish");

    // Also write to ~/.william/completions/ for consistency
    fs.mkdirSync(completionsDir, { recursive: true });
    fs.writeFileSync(scriptPath, script);

    // Check if already installed
    if (
      fs.existsSync(fishPath) &&
      fs.readFileSync(fishPath, "utf-8") === script
    ) {
      console.log(
        `Completions already installed at ${fishPath}. Nothing to do.`,
      );
      return;
    }

    fs.writeFileSync(fishPath, script);
    console.log(`Completion script written to: ${scriptPath}`);
    console.log(`Fish completions installed to: ${fishPath}`);
  } else {
    // Bash/Zsh: write script to ~/.william/completions/ and source from profile
    fs.mkdirSync(completionsDir, { recursive: true });
    fs.writeFileSync(scriptPath, script);

    const profilePath = getProfilePath(shell);
    const sourceLine = `source "${scriptPath}"`;

    if (isAlreadyInstalled(profilePath, sourceLine)) {
      console.log(
        `Completions already installed in ${profilePath}. Nothing to do.`,
      );
      return;
    }

    // Append source line to profile
    const profileExists = fs.existsSync(profilePath);
    if (profileExists) {
      const content = fs.readFileSync(profilePath, "utf-8");
      const separator = content.endsWith("\n") ? "" : "\n";
      fs.appendFileSync(
        profilePath,
        `${separator}\n# william shell completions\n${sourceLine}\n`,
      );
    } else {
      fs.writeFileSync(
        profilePath,
        `# william shell completions\n${sourceLine}\n`,
      );
    }

    console.log(`Completion script written to: ${scriptPath}`);
    console.log(`Profile updated: ${profilePath}`);
  }

  console.log(
    `\nRestart your shell or run: source ${shell === "fish" ? getProfilePath(shell) : getProfilePath(shell)} to enable completions.`,
  );
}
