import * as path from "path";

export type ShellType = "bash" | "zsh" | "fish";

/**
 * Detect the user's shell from $SHELL environment variable.
 * Returns null if the shell cannot be determined.
 */
export function detectShell(): ShellType | null {
  const shell = process.env.SHELL;
  if (!shell) return null;

  const base = path.basename(shell);
  if (base === "bash") return "bash";
  if (base === "zsh") return "zsh";
  if (base === "fish") return "fish";
  return null;
}

export function generateBashScript(): string {
  return `# william shell completions for bash
# Generated by: william completions --shell bash
# Add to ~/.bashrc or ~/.bash_profile:
#   source <(william completions --shell bash)
#   OR
#   william completions --shell bash > ~/.william/completions/william.bash && source ~/.william/completions/william.bash

_william_completions() {
  local cur prev words cword
  _init_completion || return

  local result
  result="$(william _completions --command "\${words[1]:-}" --position "$cword" -- "\${words[@]}" 2>/dev/null)"

  if [[ -n "$result" ]]; then
    COMPREPLY=($(compgen -W "$result" -- "$cur"))
  fi
}

complete -F _william_completions william
`;
}

export function generateZshScript(): string {
  return `# william shell completions for zsh
# Generated by: william completions --shell zsh
# Add to ~/.zshrc:
#   source <(william completions --shell zsh)
#   OR
#   william completions --shell zsh > ~/.william/completions/william.zsh && source ~/.william/completions/william.zsh

_william_completions() {
  local -a completions
  local result

  result="$(william _completions --command "\${words[2]:-}" --position "$CURRENT" -- "\${words[@]}" 2>/dev/null)"

  if [[ -n "$result" ]]; then
    completions=("\${(@f)result}")
    compadd -a completions
  fi
}

compdef _william_completions william
`;
}

export function generateFishScript(): string {
  return `# william shell completions for fish
# Generated by: william completions --shell fish
# Save to ~/.config/fish/completions/william.fish:
#   william completions --shell fish > ~/.config/fish/completions/william.fish

function __william_completions
  set -l tokens (commandline -opc)
  set -l current (commandline -ct)
  set -l count (count $tokens)

  set -l cmd ""
  if test $count -ge 2
    set cmd $tokens[2]
  end

  william _completions --command "$cmd" --position $count -- $tokens 2>/dev/null
end

complete -c william -f -a '(__william_completions)'
`;
}

export function generateScript(shell: ShellType): string {
  switch (shell) {
    case "bash":
      return generateBashScript();
    case "zsh":
      return generateZshScript();
    case "fish":
      return generateFishScript();
  }
}
